/**
  ******************************************************************************
  * @file    stm32xx_timerserver_conf.h
  * @author  MCD Application Team
  * @brief   Configuration file for timer server
  ******************************************************************************
  * @attention
  *
  * Copyright (c) 2014 STMicroelectronics.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */
#ifndef __STM32xx_TIMERSERVER_CONF_H
#define __STM32xx_TIMERSERVER_CONF_H

#ifdef __cplusplus
 extern "C" {
#endif

 /* Includes ------------------------------------------------------------------*/
#ifdef USE_STM32F4XX_NUCLEO
  #include "stm32f4xx_hal.h"
#endif /* USE_STM32F4XX_NUCLEO */

#ifdef USE_STM32L0XX_NUCLEO
#include "stm32l0xx_hal.h"
#endif /* USE_STM32L0XX_NUCLEO */   

#ifdef USE_STM32L4XX_NUCLEO
#include "stm32l4xx_hal.h"
#endif /* USE_STM32L4XX_NUCLEO */ 
   
#include "stm32xx_hal_timerserver_rtc.h"
#include "stm32xx_hal_timerserver_exti.h"

/** @addtogroup Middlewares
 *  @{
 */

/** @addtogroup ST
 *  @{
 */
 
/** @addtogroup TimerServer
 *  @{
 */

/** @defgroup STM32XX_TIMERSERVER_CONF
 * @{
 */
  
/* Exported constants --------------------------------------------------------*/
/* Exported types ------------------------------------------------------------*/

/** @defgroup STM32XX_TIMERSERVER_CONF_Exported_Macros
  * @{
  */

/* Exported macros -----------------------------------------------------------*/
#ifdef USE_STM32L0XX_NUCLEO
#define TIMERSERVER_TICK_VALUE	55	/** tick timer value is us */

/**
 * This value shall reflect the maximum delay there could be in the application between
 * the time the RTC interrupt is generated by the Hardware and the time when the
 * RTC interrupt handler is called
 * This time is measured in number of RTC_SYNCH_PRESCALER ticks
 *
 * A relax timing would be 1ms
 *
 * The value below are calculated for RTCCLK coming from LSI (37Khz)
 */
#define APP_RTC_HANDLER_MAX_DELAY	19	/**< 1ms x 37Khz / (RTC_ASYNCH_PRESCALER+1) */
#endif
   
#ifdef USE_STM32L4XX_NUCLEO
#define TIMERSERVER_TICK_VALUE	63	/** tick timer value is us */

/**
 * This value shall reflect the maximum delay there could be in the application between
 * the time the RTC interrupt is generated by the Hardware and the time when the
 * RTC interrupt handler is called
 * This time is measured in number of RTC_SYNCH_PRESCALER ticks
 *
 * A relax timing would be 1ms
 *
 * The value below are calculated for RTCCLK coming from LSI (32Khz)
 */
#define APP_RTC_HANDLER_MAX_DELAY	16	/**< 1ms x 32Khz / (RTC_ASYNCH_PRESCALER+1) */
#endif

#ifdef USE_STM32F4XX_NUCLEO
#define TIMERSERVER_TICK_VALUE	63	/** tick timer value is us */

/**
 * This value shall reflect the maximum delay there could be in the application between
 * the time the RTC interrupt is generated by the Hardware and the time when the
 * RTC interrupt handler is called
 * This time is measured in number of RTC_SYNCH_PRESCALER ticks
 *
 * A relax timing would be 1ms
 *
 * The value below are calculated for RTCCLK coming from LSI (32Khz)
 */
#define APP_RTC_HANDLER_MAX_DELAY	16	/**< 1ms x 32Khz / (RTC_ASYNCH_PRESCALER+1) */
#endif

/**
 * @}
 */
 
/**
 * @}
 */
 
/**
 * @}
 */
 
/**
 * @}
 */
 
/**
 * @}
 */
 
#ifdef __cplusplus
}
#endif

#endif /* __STM32xx_TIMERSERVER_CONF_H */
